-- Blue-Tech consolidated Supabase schema
-- Run this in the NEW Supabase project's SQL Editor.
-- Supabase Auth owns passwords. Never store a plaintext password in password_hash.
-- The admin bootstrap at the bottom promotes the Auth user with the configured email.

create extension if not exists pgcrypto;

-- Core identity and catalog tables
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  password_hash text,
  name text,
  phone text,
  picture text,
  provider text,
  provider_id text,
  role text not null default 'user' check (role in ('admin', 'user')),
  is_suspended boolean not null default false,
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  parent_id bigint references public.categories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade an existing categories table created before parent categories were added.
alter table public.categories add column if not exists parent_id bigint;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'categories_parent_id_fkey'
      and conrelid = 'public.categories'::regclass
  ) then
    alter table public.categories
      add constraint categories_parent_id_fkey
      foreign key (parent_id) references public.categories(id) on delete set null;
  end if;
end
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  average_rating numeric(3,2) not null default 0 check (average_rating between 0 and 5),
  review_count integer not null default 0 check (review_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku_code text not null unique,
  size_or_color text not null,
  price_adjustment numeric(10,2) not null default 0,
  stock_quantity integer not null default 0 check (stock_quantity >= 0)
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  is_primary boolean not null default false
);

-- User addresses, carts, wishlists, and orders
create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  recipient_name text not null,
  phone_number text not null,
  street_address text not null,
  city text not null,
  state text,
  zip_code text,
  landmarks text,
  country text not null,
  is_default boolean not null default false
);

-- Spring's entity model uses carts/cart_items. The simpler cart table is retained
-- for the requested Supabase API contract.
create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unique (cart_id, variant_id)
);

create table if not exists public.cart (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  unique (user_id, product_id)
);

create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade
);

create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  wishlist_id bigint not null references public.wishlists(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  added_at timestamptz not null default now(),
  unique (wishlist_id, product_id)
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  unique (user_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint references public.products(id) on delete restrict,
  quantity integer check (quantity > 0),
  address_id bigint references public.addresses(id) on delete restrict,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  status text not null default 'pending' check (status in ('pending','paid','processing','shipped','delivered','cancelled')),
  shipping_method text,
  payment_method text,
  shipping_fee numeric(12,2) default 0,
  order_address_street text,
  order_address_city text,
  order_address_country text,
  order_address_phone_number text,
  order_address_landmarks text,
  order_address_recipient text,
  ordered_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0)
);

-- Reviews, notifications, and notification preferences
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text,
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  message text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications_v2 (
  id bigint generated by default as identity primary key,
  audience text check (audience in ('USER','ADMIN')),
  user_id uuid references public.users(id) on delete cascade,
  category text check (category in ('SHOPPING','ACCOUNT','COMMUNITY','SYSTEM','SECURITY','BUSINESS','ORDER')),
  severity text not null default 'INFO' check (severity in ('INFO','SUCCESS','WARNING','ERROR')),
  title text,
  body text,
  href text,
  group_key text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  category text not null check (category in ('SHOPPING','ACCOUNT','COMMUNITY','SYSTEM','SECURITY','BUSINESS','ORDER')),
  enabled boolean not null default true,
  unique (user_id, category)
);

-- Admin, payment, shipping, content, and audit tables
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  kind text not null check (kind in ('PERCENT','FIXED')),
  coupon_value numeric(10,2) not null check (coupon_value >= 0),
  min_subtotal numeric(10,2),
  starts_at timestamptz,
  ends_at timestamptz,
  max_uses integer,
  uses integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  transaction_reference text,
  method text not null,
  status text not null,
  amount numeric(10,2) not null check (amount >= 0),
  paid_at timestamptz
);

create table if not exists public.payment_records (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  transaction_reference text,
  status text,
  payment_method text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  address_id bigint not null references public.addresses(id) on delete restrict,
  tracking_number text,
  carrier text,
  status text not null,
  delivery_notes text,
  shipped_at timestamptz
);

create table if not exists public.price_histories (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  price numeric(10,2) not null check (price >= 0),
  effective_from timestamptz not null,
  effective_to timestamptz
);

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  image_url text not null,
  label text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint,
  action text not null,
  target_table text not null,
  target_id text,
  description text,
  ip_address text,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz not null default now()
);

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  organization text,
  intended_use text not null check (intended_use in ('classroom', 'office')),
  screen_size text not null,
  quantity integer not null default 1 check (quantity > 0),
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now()
);

-- Indexes used by the backend queries
create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists product_images_product_id_idx on public.product_images(product_id);
create index if not exists product_variants_product_id_idx on public.product_variants(product_id);
create index if not exists addresses_user_id_idx on public.addresses(user_id);
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_product_id_idx on public.orders(product_id);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists wishlist_items_product_id_idx on public.wishlist_items(product_id);
create index if not exists notifications_v2_user_created_idx on public.notifications_v2(user_id, created_at desc);
create index if not exists notifications_v2_audience_created_idx on public.notifications_v2(audience, created_at desc);
create index if not exists quote_requests_created_at_idx on public.quote_requests(created_at desc);

-- Create a public profile whenever a Supabase Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, name, role)
  values (new.id, coalesce(new.email, ''), new.raw_user_meta_data ->> 'name', 'user')
  on conflict (id) do update set email = excluded.email;
  insert into public.profiles (id, email, role)
  values (new.id, coalesce(new.email, ''), 'USER')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- RLS: client access is limited to public catalog and the current user's records.
alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.cart enable row level security;
alter table public.wishlist enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "public read products" on public.products;
drop policy if exists "public read categories" on public.categories;
drop policy if exists "read own profile" on public.users;
drop policy if exists "update own profile" on public.users;
drop policy if exists "read own orders" on public.orders;
drop policy if exists "manage own cart" on public.cart;
drop policy if exists "manage own wishlist" on public.wishlist;
drop policy if exists "public read reviews" on public.reviews;
drop policy if exists "manage own reviews" on public.reviews;
drop policy if exists "read own notifications" on public.notifications;
drop policy if exists "update own notifications" on public.notifications;

create policy "public read products" on public.products for select using (true);
create policy "public read categories" on public.categories for select using (true);
create policy "read own profile" on public.users for select using (auth.uid() = id);
create policy "update own profile" on public.users for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "read own auth profile" on public.profiles;
create policy "read own auth profile" on public.profiles for select using (auth.uid() = id);
create policy "read own orders" on public.orders for select using (auth.uid() = user_id);
create policy "manage own cart" on public.cart for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "manage own wishlist" on public.wishlist for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "public read reviews" on public.reviews for select using (true);
create policy "manage own reviews" on public.reviews for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "read own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "update own notifications" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Admin bootstrap. Create this email first in Authentication > Users and set its
-- password there. This statement promotes that Auth identity immediately.
insert into public.users (id, email, role)
select id, email, 'admin'
from auth.users
where lower(email) = lower('systemadmin@ecom.rw')
on conflict (id) do update set role = 'admin';

insert into public.profiles (id, email, role)
select id, email, 'ADMIN'
from auth.users
where lower(email) = lower('systemadmin@ecom.rw')
on conflict (id) do update set role = 'ADMIN';

-- Verify the bootstrap found an Auth user before attempting login.
do $$
begin
  if not exists (select 1 from auth.users where lower(email) = lower('systemadmin@ecom.rw')) then
    raise notice 'Create systemadmin@ecom.rw in Authentication > Users, then rerun the admin bootstrap insert above.';
  end if;
end
$$;
