-- Blue-Tech NEW PROJECT RESET
-- WARNING: This permanently deletes all application tables and data in public.
-- Run only in the intended NEW Supabase project's SQL Editor.
-- Supabase Auth users are not deleted. Create/promote the admin at the bottom.

begin;

-- Remove the old mixed schema and its trigger functions.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user() cascade;

drop table if exists public.audit_logs cascade;
drop table if exists public.newsletter_subscribers cascade;
drop table if exists public.shipments cascade;
drop table if exists public.payment_records cascade;
drop table if exists public.payments cascade;
drop table if exists public.coupons cascade;
drop table if exists public.notification_preferences cascade;
drop table if exists public.notifications_v2 cascade;
drop table if exists public.notifications cascade;
drop table if exists public.reviews cascade;
drop table if exists public.order_items cascade;
drop table if exists public.orders cascade;
drop table if exists public.wishlist_items cascade;
drop table if exists public.wishlists cascade;
drop table if exists public.wishlist cascade;
drop table if exists public.cart_items cascade;
drop table if exists public.carts cascade;
drop table if exists public.cart cascade;
drop table if exists public.addresses cascade;
drop table if exists public.product_images cascade;
drop table if exists public.product_variants cascade;
drop table if exists public.price_histories cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.profiles cascade;
drop table if exists public.users cascade;

-- Identity. Auth owns passwords; public.users stores application profile data.
create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  password_hash text,
  name text,
  phone text,
  picture text,
  provider text,
  provider_id text,
  role text not null default 'user' check (role in ('admin', 'user')),
  is_suspended boolean not null default false,
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  parent_id bigint references public.categories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  average_rating numeric(3,2) not null default 0 check (average_rating between 0 and 5),
  review_count integer not null default 0 check (review_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku_code text not null unique,
  size_or_color text not null,
  price_adjustment numeric(10,2) not null default 0,
  stock_quantity integer not null default 0 check (stock_quantity >= 0)
);

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  is_primary boolean not null default false
);

create table public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  recipient_name text not null,
  phone_number text not null,
  street_address text not null,
  city text not null,
  state text,
  zip_code text,
  landmarks text,
  country text not null,
  is_default boolean not null default false
);

create table public.cart (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  unique (user_id, product_id)
);

create table public.carts (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  updated_at timestamptz not null default now()
);

create table public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unique (cart_id, variant_id)
);

create table public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  unique (user_id, product_id)
);

create table public.wishlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade
);

create table public.wishlist_items (
  id bigint generated by default as identity primary key,
  wishlist_id bigint not null references public.wishlists(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  added_at timestamptz not null default now(),
  unique (wishlist_id, product_id)
);

create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint references public.products(id) on delete restrict,
  quantity integer check (quantity > 0),
  address_id bigint references public.addresses(id) on delete restrict,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  status text not null default 'pending' check (status in ('pending','paid','processing','shipped','delivered','cancelled')),
  shipping_method text,
  payment_method text,
  shipping_fee numeric(12,2) not null default 0,
  order_address_street text,
  order_address_city text,
  order_address_country text,
  order_address_phone_number text,
  order_address_landmarks text,
  order_address_recipient text,
  ordered_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0)
);

create table public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text,
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  message text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.notifications_v2 (
  id bigint generated by default as identity primary key,
  audience text check (audience in ('USER','ADMIN')),
  user_id uuid references public.users(id) on delete cascade,
  category text check (category in ('SHOPPING','ACCOUNT','COMMUNITY','SYSTEM','SECURITY','BUSINESS','ORDER')),
  severity text not null default 'INFO' check (severity in ('INFO','SUCCESS','WARNING','ERROR')),
  title text,
  body text,
  href text,
  group_key text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.notification_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  category text not null check (category in ('SHOPPING','ACCOUNT','COMMUNITY','SYSTEM','SECURITY','BUSINESS','ORDER')),
  enabled boolean not null default true,
  unique (user_id, category)
);

create table public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  kind text not null check (kind in ('PERCENT','FIXED')),
  coupon_value numeric(10,2) not null check (coupon_value >= 0),
  min_subtotal numeric(10,2),
  starts_at timestamptz,
  ends_at timestamptz,
  max_uses integer,
  uses integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  transaction_reference text,
  method text not null,
  status text not null,
  amount numeric(10,2) not null check (amount >= 0),
  paid_at timestamptz
);

create table public.payment_records (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  transaction_reference text,
  status text,
  payment_method text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table public.shipments (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  address_id bigint not null references public.addresses(id) on delete restrict,
  tracking_number text,
  carrier text,
  status text not null,
  delivery_notes text,
  shipped_at timestamptz
);

create table public.price_histories (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  price numeric(10,2) not null check (price >= 0),
  effective_from timestamptz not null,
  effective_to timestamptz
);

create table public.hero_slides (
  id bigint generated by default as identity primary key,
  image_url text not null,
  label text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  action text not null,
  target_table text not null,
  target_id text,
  description text,
  ip_address text,
  created_at timestamptz not null default now()
);

create table public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz not null default now()
);

-- Public product images. Uploads are performed by the admin-only Edge Function.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

-- Profile rows are created automatically for new Auth accounts.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, name, role)
  values (new.id, coalesce(new.email, ''), new.raw_user_meta_data ->> 'name', 'user');
  insert into public.profiles (id, email, role)
  values (new.id, coalesce(new.email, ''), 'USER');
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- RLS for direct Supabase client access. The Edge Function uses its own guards.
alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.cart enable row level security;
alter table public.wishlist enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;

create policy "public read categories" on public.categories for select using (true);
create policy "public read products" on public.products for select using (true);
create policy "read own users row" on public.users for select using (auth.uid() = id);
create policy "update own users row" on public.users for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "read own profile row" on public.profiles for select using (auth.uid() = id);
create policy "read own orders" on public.orders for select using (auth.uid() = user_id);
create policy "manage own cart" on public.cart for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "manage own wishlist" on public.wishlist for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "public read reviews" on public.reviews for select using (true);
create policy "manage own reviews" on public.reviews for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "read own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "update own notifications" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Promote the existing Auth account. This does not create a password.
insert into public.users (id, email, role)
select id, email, 'admin'
from auth.users
where lower(email) = lower('systemadmin@ecom.rw')
on conflict (id) do update set role = 'admin';

insert into public.profiles (id, email, role)
select id, email, 'ADMIN'
from auth.users
where lower(email) = lower('systemadmin@ecom.rw')
on conflict (id) do update set role = 'ADMIN';

commit;

-- After running this script, create systemadmin@ecom.rw under
-- Authentication > Users if it does not already exist, set its password,
-- then rerun the two promotion INSERT statements above.
