-- Backs the admin Hero Slides manager (homepage carousel) and the admin Audit Log
-- page — both already shipped in the frontend but had no matching backend route or
-- table, so every request 501'd. Written by the api edge function's service-role
-- client only (same pattern as every other table in this schema) — hero_slides also
-- gets a narrow anon-read policy since the homepage carousel is public.

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  image_url text not null,
  label text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint,
  action text not null,
  target_table text not null,
  target_id text,
  description text,
  ip_address text,
  created_at timestamptz not null default now()
);

alter table public.hero_slides enable row level security;
alter table public.audit_logs enable row level security;

create policy "public can read active hero slides"
  on public.hero_slides for select
  using (is_active = true);

create index if not exists hero_slides_sort_order_idx on public.hero_slides(sort_order);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);

notify pgrst, 'reload schema';
