-- Backs the Interactive Screens "Configurations" section's Request-a-Quote flow.
-- Written by the api edge function's service-role client only (same pattern as every
-- other table in this schema) — no anon/public policies needed.

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  organization text,
  intended_use text not null check (intended_use in ('classroom', 'office')),
  screen_size text not null,
  quantity integer not null default 1 check (quantity > 0),
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.quote_requests enable row level security;

create index if not exists quote_requests_created_at_idx on public.quote_requests(created_at desc);

notify pgrst, 'reload schema';
