-- Blue-Tech core schema for the new Supabase project.
-- Supabase Auth owns passwords. public.users.password_hash is retained only
-- for legacy compatibility and must never contain a plaintext password.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  password_hash text,
  is_suspended boolean not null default false,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(12, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  status text not null default 'pending' check (status in ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  unique (user_id, product_id)
);

create table if not exists public.cart (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  unique (user_id, product_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_product_id_idx on public.orders(product_id);
create index if not exists wishlist_user_id_idx on public.wishlist(user_id);
create index if not exists cart_user_id_idx on public.cart(user_id);
create index if not exists reviews_product_id_idx on public.reviews(product_id);
create index if not exists notifications_user_id_read_idx on public.notifications(user_id, read);

-- Keep a public profile synchronized for every Auth user.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, role)
  values (new.id, coalesce(new.email, ''), 'user')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.wishlist enable row level security;
alter table public.cart enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;

create policy "public can read products" on public.products for select using (true);
create policy "public can read categories" on public.categories for select using (true);
create policy "users can read own profile" on public.users for select using (auth.uid() = id);
create policy "users can update own profile" on public.users for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "users can read own orders" on public.orders for select using (auth.uid() = user_id);
create policy "users can manage own wishlist" on public.wishlist for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users can manage own cart" on public.cart for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users can read reviews" on public.reviews for select using (true);
create policy "users can manage own reviews" on public.reviews for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users can read own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "users can update own notifications" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Admin seed: create the Auth account first in Authentication > Users using
-- the desired password, then run this insert with that Auth user's UUID.
-- The UUID is deliberately not fabricated because public.users.id must equal
-- auth.users.id for Supabase login and RLS to work.
--
-- insert into public.users (id, email, role)
-- values ('<auth-user-uuid>', 'systemadmin@ecom.rw', 'admin')
-- on conflict (id) do update set role = 'admin';
